### ISSUE TITLE
Please put back the S3 files

### ISSUE THREAD

**Issue by sverraest** [aws-quickstart/quickstart-mongodb-atlas#39]
Hi there, we're using the MongoDB Atlas resources registration template from this bucket, however the files seem to be removed.
Any chance these can be put back to avoid breaking infrastructure changes?

**Comment by sverraest** [comment]
The missing file is `register-mongodb-atlas-resources.yaml`

**Comment by sverraest** [comment]
```
Resources:
  RegisterAtlasResources:
    Condition: RegisterResources
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/register-mongodb-atlas-resources.yaml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
```

This file is no longer available
